version: "3.9"
services:
    redis:
        hostname: redis
        networks:
            - server-network
        image: redis
        ports:
            - "6379:6379"
        command: ["sh", "-c", "exec redis-server --requirepass \"password\""]

    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
        networks:
            - server-network
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
            - ./docker/mariadb/dumps:/dumps

    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - server-network

    php:
        build: docker/php
        volumes:
            - ./:/var/www
        networks:
            - server-network

networks:
    server-network:
        external: true
